### ISSUE TITLE
Internal anchor links open in Safari even when in web app mode on iPhone

### ISSUE THREAD

**Issue by geealbers** [gettypubs/osci-report#17]
In configuring the report as a web app for Apple (`<meta content='yes' name='apple-mobile-web-app-capable'>`) everything seems to work okay **except** that internal anchor links (`#lesson-1`) open in Safari rather than within the web app. You can see the behavior in the two grid pages, which are all triggered with anchor links, and on the Three Approaches page, with the top `<li>`s which are anchor links to sections in the content below. Other internal links, from chapter to chapter, seem to behave as expected.

**Comment by geealbers** [comment]
@egardner can you take a look at this and let me know if there is a quick and obvious fix you could make? If there's not I'll strip the web-app capability out

**Comment by egardner** [comment]
@geealbers I'll take a look and see if there's a simple solution.

**Comment by egardner** [comment]
I've attempted to fix that here: 5542953273d89578ada5a580bb8721fc956694fe, based on the solution in this post: https://www.bennadel.com/blog/2302-preventing-links-in-standalone-iphone-applications-from-opening-in-mobile-safari.htm

There are a few other solutions floating around but this one is straightforward and didn't seem to break anything. Please give it a try and I'll close this if you don't notice any problems.

**Comment by geealbers** [comment]
Worked!
